### ISSUE TITLE
All spawners in bo3's are pig spawners in builds 150+ (Spigot 1.10)

### ISSUE THREAD

**Issue by MCPitman** [MCTCP/TerrainControl#460]
Tested bo3s with various mob spawners, builds 150 and up place pig spawners only. Build 149 works fine (Spigot 1.10).

**Comment by BakermanLP** [comment]
This is, in my opinion, no problem with TerrainControl. I think, that is a new structure or new data in the nbt files. This seems to be a 1.10 change. The old nbt file contained:
```
? ''
: - EntityId: Zombie
  - MaxNearbyEntities: !short "6"
  - RequiredPlayerRange: !short "16"
  - SpawnCount: !short "4"
  - id: MobSpawner
  - MaxSpawnDelay: !short "800"
  - SpawnRange: !short "4"
  - Delay: !short "0"
  - MinSpawnDelay: !short "200"
```

The new nbt data contains the following:
```
? ''
: - MaxNearbyEntities: !short "6"
  - RequiredPlayerRange: !short "16"
  - SpawnCount: !short "4"
  - SpawnData:
    - id: Zombie
  - MaxSpawnDelay: !short "800"
  - Delay: !short "0"
  - SpawnRange: !short "4"
  - MinSpawnDelay: !short "200"
  - SpawnPotentials: !list_compound
    - - Entity:
        - id: Zombie
      - Weight: 1
  - id: MobSpawner

```

I git a demonstation nbt from ZoefyC on the mctcp forum. Here it is:

[MobSpawner.zip](https://github.com/MCTCP/TerrainControl/files/495019/MobSpawner.zip)

Please try it out and comment here.

Michael (aka BakermanLP)
