### ISSUE TITLE
Suggestion: Add 'HideTutorials' Setting.

### ISSUE THREAD

**Issue by JohannesMP** [MCTCP/TerrainControl#73]
Note: [related discussion on the TC Bukkit forum](http://dev.bukkit.org/server-mods/terrain-control/forum/41750-suggestion-ability-to-disable-verboseness-of-biome/).

When TC generates the Biome Terrain Files it currently always includes a ton of 'tutorial' documentation for each variable. This is great for a first-time user of TC, but if you're trying to compare values of a few dozen Biomes it's impossible to currently do so efficiently.

There is just too much text in the way! Even more annoying is that TC always re-generates the file, so even if I go through and remove the extra stuff, the moment I run TC again it just re-creates the file and puts all the unnecessary text back!

I would like to request a "HideTutorials" config setting for TC that would omit the unnecessary info from the config files if it is set to true. It would be false by default.

In short I want to change this:

``` YAML
#######################################################################
# +-----------------------------------------------------------------+ #           
# |                          Derp biome config                      | #
# +-----------------------------------------------------------------+ #
#######################################################################

# Biome size from 0 to GenerationDepth. Show in what zoom level biome will be generated (see GenerationDepth)
# Higher numbers=Smaller% of world / Lower numbers=Bigger % of world
# Don`t work on Ocean and River (frozen versions too) biomes until not added as normal biome.
BiomeSize:4

# Biome rarity from 100 to 1. If this is normal or ice biome - chance for spawn this biome then others.
# Example for normal biome :
#   100 rarity mean 1/6 chance than other ( with 6 default normal biomes).
#   50 rarity mean 1/11 chance than other
# For isle biome this is chance to spawn isle in good place.
# Don`t work on Ocean and River (frozen versions too) biomes until not added as normal biome.
BiomeRarity:98

# Biome color in hex value. Biome color in /tc map command
BiomeColor:0x5e83e8

# True if biome can pass rivers.
BiomeRivers:true

# Biome name list where this biome will be spawned as isle. Like Mushroom isle in Ocean.  This work only if this biome is in IsleBiomes in world config
IsleInBiome:

# Biome name list where this biome will be border.Like Mushroom isle shore. Use is compared as IsleInBiome
BiomeIsBorder:

# Biome name list near border is not applied. 
NotBorderNear:

# Biome temperature. Float value from 0.0 to 1.0
BiomeTemperature:0.5

# Biome wetness. Float value from 0.0 to 1.0
BiomeWetness:0.5


#######################################################################
# +-----------------------------------------------------------------+ #
# |                   Terrain Generator Variables                   | #
# +-----------------------------------------------------------------+ #
#######################################################################

...
```

To this:

``` YAML
# +-----------------------------------------------------------------+ #
# |                          Derp biome config                      | #
# +-----------------------------------------------------------------+ #

BiomeSize:4
BiomeRarity:98
BiomeColor:0x5e83e8
BiomeRivers:true
IsleInBiome:
BiomeIsBorder:
NotBorderNear:
BiomeTemperature:0.5
BiomeWetness:0.5

# +-----------------------------------------------------------------+ #
# |                   Terrain Generator Variables                   | #
# +-----------------------------------------------------------------+ #

...
```

Isn't that much neater? It's soooooo much easier to read, and has the added benefit of taking up much less harddrive space.

The 'HideTutorials' setting could either be global (requiring a single config.ini file, likely in the plugins/TerrainControl/ folder), or it could be defined on a per-world basis, at the top of each 'WorldConfig' file.

Once 'HideTutorials' is enabled it would re-create the Biome/World Config files without the text the next time you run `/tc reload` or `/tc check <world>`.
